### ISSUE TITLE
UNAUTHORIZED USER

### ISSUE THREAD

**Issue by LifeIsStrangeFan** [sunnyelf/pyonlinedict#1]
![error](https://cloud.githubusercontent.com/assets/23134571/25565940/838bf176-2e03-11e7-9c75-8e97742e2a2c.png)

How can I fix it?
**thanks.**

**Comment by shmilylty** [comment]
set your baidu translate appid and secreKey in pyonliedict 127 and 128 line  

appid = '2015063000000001'
secretKey = '12345678'
is defaluat username and password in http://api.fanyi.baidu.com/api/trans/product/apidoc.

your appid and secret key in http://api.fanyi.baidu.com/api/trans/product/desktop?req=developer
